CREATE DATABASE DB_TEXTURA;
USE DB_TEXTURA;

CREATE TABLE RGB_COLOR(
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	NOM_COLOR CHAR(100),
	R1 INT,
	G1 INT,
	B1 INT,
);

USE DB_DENUNCIAS

DROP DATABASE DB_TEXTURA

-- CADENA DE CONEXIÓN: Data Source=localhost;Initial Catalog=DB_TEXTURA;Integrated Security=True